FROM continuumio/miniconda3
WORKDIR ~
COPY CellBender CellBender
SHELL ["/bin/bash", "--login", "-c"]
RUN conda create -y -n cellbender --quiet python=3.7 && \
	conda init bash && \
	conda activate cellbender && \
	conda install -c anaconda -y pytables && \
	yes | pip install torch &&  \ 
	yes | pip install -e CellBender && \
	apt-get update && \
	apt-get install -y curl && \
	apt-get install -y bc && \
	curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
	apt-get install -y unzip && \
	unzip awscliv2.zip && \
	./aws/install
WORKDIR ~/cellranger
COPY check_shutdown.sh entrypoint.sh .
RUN chmod 777 entrypoint.sh && chmod 777 check_shutdown.sh
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "cellbender", "./entrypoint.sh"]
